[build]
target = "riscv32imac-unknown-none-elf"
rustflags = [
    "-C", "link-arg=-Tqemu_virt.ld",
    "-C", "link-arg=--omagic"
]

# needed to enable "C(ompressed)" extension for ECLIC interrupt to
# auto adjust +2 or +4 for mepc when thee
[target.riscv32imac-unknown-none-elf]
runner = """
qemu-system-riscv32
  -cpu rv32,c=true
  -machine virt
  -m 150M
  -s
  -nographic
  -serial mon:stdio
  -bios
"""


