[build]
target = "riscv32imac-unknown-none-elf"
rustflags = [
    "-C", "link-arg=-Tqemu_virt.ld",
    "-C", "link-arg=--omagic"
]


[target.riscv32imac-unknown-none-elf]
runner = """
qemu-system-riscv32
  -cpu rv32
  -machine virt
  -m 150M
  -s
  -nographic
  -serial mon:stdio
  -bios
"""


